# Generated by Django 4.1.4 on 2023-10-15 09:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dentease', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Denstist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=150)),
                ('clinicAddress', models.CharField(default='', max_length=100)),
                ('contact', models.CharField(default='', max_length=10)),
                ('description', models.CharField(default='Edit Profile to add description', max_length=500)),
                ('location', models.CharField(default='Edit profile to add location', max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
